name: Zip-1.12-2048X

on:
  push:
    tags:
      - "v*"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: assets/ LICENSE README.md pack.mcmeta pack.png
          dest: ER2K_1.12_PBR_2048X_${{ steps.get_version.outputs.VERSION }}.zip
