name: Zip-1.12-1024X

# 提交tag触发流水线
on:
  push:
    tags:
    - 'v*'


jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      # 压缩zip包
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: assets/ LICENSE README.md pack.mcmeta pack.png
          dest: ER2K_1.12_PBR_1024X_${{ steps.get_version.outputs.VERSION }}.zip
      # 创建Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      # 上传zip包
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ER2K_1.12_PBR_1024X_${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: ER2K_1.12_PBR_1024X_${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
